FROM golang:1.24.3-alpine3.22@sha256:b4f875e650466fa0fe62c6fd3f02517a392123eea85f1d7e69d85f780e4db1c1

RUN apk add alpine-sdk

COPY . /dist/core

RUN cd /dist/core && \
    go test -coverprofile=coverage.out -covermode=atomic -v ./...
